// This file is auto-generated by set-env.js
export const BASE_URL: string = "http://localhost:8080/api/";
export const HEALTH_URL: string = "http://localhost:8080/actuator/health/";
export const API_VERSION: string = "1.1";
