spring.config.activate.on-profile=dev
# Make the SQL readable
spring.jpa.properties.hibernate.format_sql=true
logging.console.enabled=true
# Establish minimum threshold. show: DEBUG, INFO, WARN, ERROR
logging.level.org.hibernate.SQL=DEBUG
# To see the actual data being passed into the query
logging.level.org.hibernate.orm.jdbc.bind=trace
# Use to enable syntax highlighting (color coding) for the SQL queries
spring.jpa.properties.hibernate.highlight_sql=true
# Provides dashboard for application's overall database performance
spring.jpa.properties.hibernate.generate_statistics=true
