const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const targetPath = path.join(__dirname, 'src/app/shared/api/base.ts');

let envConfig = {
  NG_APP_BASE_URL: 'http://localhost:8080/api/',
  NG_APP_HEALTH_URL: 'http://localhost:8080/actuator/health/',
  NG_APP_API_VERSION: '1.1'
};

if (fs.existsSync(envPath)) {
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split('\n').forEach(line => {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let value = match[2] || '';
      // Remove surrounding quotes if any
      if (value.length > 0 && value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
        value = value.substring(1, value.length - 1);
      }
      if (value.length > 0 && value.charAt(0) === "'" && value.charAt(value.length - 1) === "'") {
        value = value.substring(1, value.length - 1);
      }
      envConfig[key] = value.trim();
    }
  });
} else {
  console.log('.env file not found, using default environment variables.');
}

const content = `// This file is auto-generated by set-env.js
export const BASE_URL: string = "${envConfig.NG_APP_BASE_URL || 'http://localhost:8080/api/'}";
export const HEALTH_URL: string = "${envConfig.NG_APP_HEALTH_URL || 'http://localhost:8080/actuator/health/'}";
export const API_VERSION: string = "${envConfig.NG_APP_API_VERSION || '1.1'}";
`;

fs.writeFileSync(targetPath, content, 'utf8');
console.log(`Successfully generated ${targetPath}`);
